server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sg_blog?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#不设置Redis则使用时默认连接本机的默认端口，要想正常使用需要在本机的默认端口上启动Redis服务端
#oss为前缀，用于记录信息给其他类进行读取
oss:
#  ps：已经进行错乱处理
  accessKey: -ffA25Q9-m-hrdlXisjfksjfYbCO3PgsnqmpPA54
  secretKey: _doQZKm4djfkddzd5Z_BAOe4IdNZZsjfsOCsRAW
  bucket: kana-2


